---

- hosts: 192.168.10.40
  become: true
  tasks:
  
  - name: Installing HTTPD Server
    yum:
      name: httpd
      state: latest
      #update_cache: true
    when: ansible_distribution == "CentOS"
