---

- hosts: apt
  become: true
  tasks:
  
          
  - name: Update Repository Index
    apt:
       update_cache: yes


  - name: Installing PHP Support for Apache2
    apt:
       name: libapache2-mod-php
       state: latest

  - name: Installing Apache2 Service
    apt:
      name: apache2
      state: latest
