---

- hosts: all 
  become: true
  tasks:
  
  - name: Installing Apache2 & PHP Support along with Cache Update
    apt:
       name:
          - nmap
            #- libapache2-mod-php
       state: latest
       update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: Installing HTTPD & PHP Support Along with Cache Update
    yum:
       name:
          - nmap
            #- php
       state: latest
       update_cache: yes
    when: ansible_distribution == "CentOS"

